[package]
name = "xtask"
version = "0.1.0"
authors = ["Vincent Tavernier <vince.tavernier@gmail.com>"]
edition = "2018"

[dependencies]
gl_generator = { version = "0.14", features = ["unstable_generator_utils"] }
heck = "0.3"
paw = "1.0"
structopt = { version = "0.3", features = ["paw"] }
