[package]
name = "tinygl-compiler"
version = "0.1.0"
authors = ["Vincent Tavernier <vincent.tavernier@inria.fr>"]
edition = "2018"
license = "MIT"

[dependencies]
shaderc = "0.6.2"
heck = "0.3.1"
spirv_cross = { version = "0.18.0", features = ["glsl"] }
rspirv = { git = "https://github.com/gfx-rs/rspirv.git", rev = "3905855" }
spirv_headers = { git = "https://github.com/gfx-rs/rspirv.git", rev = "3905855" }
sha2 = "0.8.1"
base64 = "0.12.0"
